
name: deploy-website

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v5.0.0
        with:
            node-version: '20.X'
      - name: install dependencies
        run: yarn install
      - name: build
        run: yarn build
      - name: copy dist file with scp
        uses: appleboy/scp-action@v0.0.1
        with:
            host: “47.99.104.154”
            username: “root”
            password: “xiaoran@666”
            source: dist/*
            target: /var/www/myfrontend/
 