
name: deploy-website

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v5.0.0
        with:
            node-version: '20.X'
      - name: install dependencies
        run: yarn install
      - name: build
        run: yarn build
      - name: copy dist file with scp
        uses: appleboy/scp-action@v0.1.8
        with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            password: ${{ secrets.SERVER_PASSWORD }}
            source: 'dist/*'
            target: '/var/www/myfrontend/'
 